parameters:
  app_name: Nicben
  mail_from_name: '%env(MAILER_FROM_NAME)%'
  mail_from_email: '%env(MAILER_FROM_EMAIL)%'
  locale: es
  locales:
    - { language: es, name: Español, icon: es }
#    - { language: en, name: English, icon: us }
